spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_bank?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root  # 加密（生产环境使用），需要配置解密
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver # mysql 8.x要加“cj”
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000 # 配置获取连接等待超时的时间
      validation-query: SELECT 1 # 验证连接
      validation-query-timeout: 2000

  ###Redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
    password:

    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
  mail:
    host: smtp.qq.com
    username: 1714015226@qq.com
    password: udbgqtmqbycwbcca
    protocol: smtp
    default-encoding: utf-8
### jwt
jwt:
  ###过期时间
  time: 18000 # (300分钟)
  ###安全密钥
  secret: "itemBankSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"

mybatis:
  ### 数据库模型对象
  type-aliases-package: com.item_backend.model.entity
  mapper-locations: mapper/*.xml

logging:
  level:
    root: error
  path: /home/log/item_backend_v1.0

server:
  port: 9000

pagehelper:
  helper-dialect: mysql
  params: count,countSql
  reasonable: true
  support-methods-arguments: true

#七牛的配置
qiniu:
    accessKey: PiZfyaRbuJE7moSwfNVrIoj1VLRBsQivxXpO91Pf
    secretKey: nk_xC4js0f11jAOigSzpAMh28_efHMFE8kaW0hyD
    bucketName: itembank2954
    fileDomain: http://qcrp47k4o.bkt.clouddn.com #文件访问域名前缀
